version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: django-backend
    env_file:
      - .env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - 8000
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: react-frontend
    depends_on:
      - backend
    volumes:
      - react_build:/app/build

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/static
      - media_volume:/app/media
      - react_build:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend

volumes:
  static_volume:
  react_build: